version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ebay_marketplace
      POSTGRES_USER: ebayuser
      POSTGRES_PASSWORD: ebaypassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka
    ports:
      - "9092:9092"
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

volumes:
  postgres_data:
