services:
  - type: web
    name: ebay-app
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/ebay-0.0.1-SNAPSHOT.jar --server.port=$PORT
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false