AWSConfigurationTemplateVersion: 1.1.0.0
EnvironmentConfigurationMetadata:
  DateCreated: '1759558659000'
  DateModified: '1759558804531'
  Description: Configuration created from the EB CLI using "eb config save".
EnvironmentTier:
  Name: WebServer
  Type: Standard
OptionSettings:
  aws:autoscaling:launchconfiguration:
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
  aws:autoscaling:updatepolicy:rollingupdate:
    RollingUpdateEnabled: true
    RollingUpdateType: Health
  aws:ec2:instances:
    InstanceTypes: t3.medium
  aws:elasticbeanstalk:application:environment:
    AWS_DB_HOST: ebay-postgres-db.cgzibuqw7bgx.us-east-2.rds.amazonaws.com
    AWS_DB_NAME: ebay_marketplace
    AWS_DB_PASSWORD: ebaypassword123
    AWS_DB_PORT: '5432'
    AWS_DB_USERNAME: ebayuser
    JAVA_OPTS: -Xmx1536m -Xms1024m
    LOGGING_LEVEL_ORG_HIBERNATE: WARN
    SERVER_PORT: '5000'
    SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE: '5'
    SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_INSERTS: true
    SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES: true
    SPRING_JPA_SHOW_SQL: false
    SPRING_PROFILES_ACTIVE: production
  aws:elasticbeanstalk:command:
    BatchSize: '30'
    BatchSizeType: Percentage
  aws:elasticbeanstalk:environment:
    LoadBalancerType: application
    ServiceRole: aws-elasticbeanstalk-service-role
  aws:elasticbeanstalk:healthreporting:system:
    SystemType: enhanced
  aws:elb:loadbalancer:
    CrossZone: true
  aws:elb:policies:
    ConnectionDrainingEnabled: true
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:us-east-2::platform/Corretto 17 running on
    64bit Amazon Linux 2023/4.6.5
